
CREATE TABLE AUTHS
(
  AUTH_ID   VARCHAR(200) NOT NULL COMMENT '권한 대표값',
  AUTH_NAME VARCHAR(200) NOT NULL COMMENT '권한명',
  PRIMARY KEY (AUTH_ID)
) COMMENT '권한들';

CREATE TABLE QUESTIONS
(
  QUESTIONS_ID VARCHAR(200) NOT NULL COMMENT '질문 대표값',
  QUESTION     VARCHAR(200) NOT NULL COMMENT '질문',
  PRIMARY KEY (QUESTIONS_ID)
) COMMENT '질문들';

CREATE TABLE RESERVATIONS
(
  RESERVATION_ID VARCHAR(200) NOT NULL COMMENT '투숙내역 대표값',
  CHECK_IN       TIMESTAMP    NOT NULL COMMENT '체크인날짜',
  CHECK_OUT      TIMESTAMP    NOT NULL COMMENT '체크아웃 날짜',
  USER_ID        VARCHAR(200) NOT NULL COMMENT '사용자 대표값',
  PRIMARY KEY (RESERVATION_ID)
) COMMENT '투숙내역';

CREATE TABLE SURVEYS
(
  USER_ID      VARCHAR(200) NOT NULL COMMENT '사용자 대표값',
  QUESTIONS_ID VARCHAR(200) NOT NULL COMMENT '질문 대표값',
  ANSWER      INTEGER      NULL     COMMENT '객관식 응답 ',
  ETC_ANSWER   VARCHAR(200) NULL     COMMENT '서술형 응답'
) COMMENT '실제설문';

CREATE TABLE USERS
(
  USER_ID  VARCHAR(200) NOT NULL COMMENT '사용자 대표값',
  LOGIN_ID VARCHAR(200) NOT NULL COMMENT '로그인 아이디',
  LOGIN_PW VARCHAR(200) NOT NULL COMMENT '로그인 비밀번호',
  NAME     VARCHAR(200) NOT NULL COMMENT '사용자이름',
  AUTH_ID  VARCHAR(200) NOT NULL COMMENT '권한 대표값',
  PRIMARY KEY (USER_ID)
) COMMENT '사용자들';

ALTER TABLE USERS
  ADD CONSTRAINT FK_AUTHS_TO_USERS
    FOREIGN KEY (AUTH_ID)
    REFERENCES AUTHS (AUTH_ID);

ALTER TABLE RESERVATIONS
  ADD CONSTRAINT FK_USERS_TO_RESERVATIONS
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID);

ALTER TABLE SURVEYS
  ADD CONSTRAINT FK_USERS_TO_SURVEYS
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID);

ALTER TABLE SURVEYS
  ADD CONSTRAINT FK_QUESTIONS_TO_SURVEYS
    FOREIGN KEY (QUESTIONS_ID)
    REFERENCES QUESTIONS (QUESTIONS_ID);
