
CREATE TABLE ANSWERS
(
  ANSWER    INTEGER      NOT NULL COMMENT '답항',
  ANSWER_ID VARCHAR(200) NOT NULL COMMENT '답항 대표값',
  PRIMARY KEY (ANSWER_ID)
) COMMENT '설문답항';

CREATE TABLE AUTHS
(
  AUTH_ID   VARCHAR(200) NOT NULL COMMENT '권한 대표값',
  AUTH_NAME VARCHAR(200) NOT NULL COMMENT '권한명',
  PRIMARY KEY (AUTH_ID)
) COMMENT '권한들';

CREATE TABLE QUE_ANS
(
  QUESTION_ID VARCHAR(200) NOT NULL COMMENT '질문 대표값',
  ANSWER_ID   VARCHAR(200) NOT NULL COMMENT '답항 대표값'
) COMMENT '문항과답';

CREATE TABLE QUESTIONS
(
  QUESTION    VARCHAR(200) NOT NULL COMMENT '질문',
  QUESTION_ID VARCHAR(200) NOT NULL COMMENT '질문 대표값',
  PRIMARY KEY (QUESTION_ID)
) COMMENT '질문들';

CREATE TABLE RESERVATIONS
(
  RESERVATION_ID VARCHAR(200) NOT NULL COMMENT '투숙내역 대표값',
  CHECK_IN       TIMESTAMP    NOT NULL COMMENT '체크인날짜',
  CHECK_OUT      TIMESTAMP    NOT NULL COMMENT '체크아웃 날짜',
  USER_ID        VARCHAR(200) NOT NULL COMMENT '사용자 대표값',
  PRIMARY KEY (RESERVATION_ID)
) COMMENT '투숙내역';

CREATE TABLE SURVEYS
(
  USER_ID     VARCHAR(200) NOT NULL COMMENT '사용자 대표값',
  QUESTION_ID VARCHAR(200) NOT NULL COMMENT '질문 대표값',
  ANSWER_ID   VARCHAR(200) NOT NULL COMMENT '답항 대표값'
) COMMENT '실제설문';

CREATE TABLE USERS
(
  USER_ID  VARCHAR(200) NOT NULL COMMENT '사용자 대표값',
  LOGIN_ID VARCHAR(200) NOT NULL COMMENT '로그인 아이디',
  LOGIN_PW VARCHAR(200) NOT NULL COMMENT '로그인 비밀번호',
  NAME     VARCHAR(200) NOT NULL COMMENT '사용자이름',
  AUTH_ID  VARCHAR(200) NOT NULL COMMENT '권한 대표값',
  PRIMARY KEY (USER_ID)
) COMMENT '사용자들';

ALTER TABLE USERS
  ADD CONSTRAINT FK_AUTHS_TO_USERS
    FOREIGN KEY (AUTH_ID)
    REFERENCES AUTHS (AUTH_ID);

ALTER TABLE RESERVATIONS
  ADD CONSTRAINT FK_USERS_TO_RESERVATIONS
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID);

ALTER TABLE SURVEYS
  ADD CONSTRAINT FK_USERS_TO_SURVEYS
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID);

ALTER TABLE QUE_ANS
  ADD CONSTRAINT FK_QUESTIONS_TO_QUE_ANS
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTIONS (QUESTION_ID);

ALTER TABLE SURVEYS
  ADD CONSTRAINT FK_QUESTIONS_TO_SURVEYS
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTIONS (QUESTION_ID);

ALTER TABLE QUE_ANS
  ADD CONSTRAINT FK_ANSWERS_TO_QUE_ANS
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWERS (ANSWER_ID);

ALTER TABLE SURVEYS
  ADD CONSTRAINT FK_ANSWERS_TO_SURVEYS
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWERS (ANSWER_ID);
