
CREATE TABLE ANSWERS
(
  ANSWER_ID VARCHAR(255) NOT NULL COMMENT '응답 아이디',
  ANSWER    INTEGER      NOT NULL COMMENT '응답 내용',
  PRIMARY KEY (ANSWER_ID)
) COMMENT '응답들';

CREATE TABLE QUE_ANS
(
  QUESTION_ID VARCHAR(255) NOT NULL COMMENT '질문 아이디',
  ANSWER_ID   VARCHAR(255) NOT NULL COMMENT '응답 아이디'
) COMMENT '문항과 답들';

CREATE TABLE QUESTIONS
(
  QUESTION_ID VARCHAR(255) NOT NULL COMMENT '질문 아이디',
  QUESTION    VARCHAR(255) NOT NULL COMMENT '질문 내용',
  PRIMARY KEY (QUESTION_ID)
) COMMENT '질문들';

CREATE TABLE RESERVATIONS
(
  RESERV_ID VARCHAR(255) NOT NULL COMMENT '예약번호',
  USER_ID   VARCHAR(255) NOT NULL COMMENT '사용자 고유 아이디',
  CHECK_IN  TIMESTAMP    NOT NULL COMMENT '체크인',
  CHECK_OUT TIMESTAMP    NOT NULL COMMENT '체크아웃',
  PRIMARY KEY (RESERV_ID)
) COMMENT '예약 내역들';

CREATE TABLE USER_RESERV_QA
(
  RESERV_ID   VARCHAR(255) NOT NULL COMMENT '예약번호',
  QUESTION_ID VARCHAR(255) NOT NULL COMMENT '질문 아이디',
  ANSWER_ID   VARCHAR(255) NOT NULL COMMENT '응답 아이디'
) COMMENT '사용자_예약_질의응답';

CREATE TABLE USERS
(
  USER_ID  VARCHAR(255) NOT NULL COMMENT '사용자 고유 아이디',
  LOGIN_ID VARCHAR(255) NOT NULL COMMENT '로그인 아이디',
  LOGIN_PW VARCHAR(255) NOT NULL COMMENT '로그인 비밀번호',
  NAME     VARCHAR(255) NOT NULL COMMENT '사용자명',
  PRIMARY KEY (USER_ID)
) COMMENT '유저들';

ALTER TABLE RESERVATIONS
  ADD CONSTRAINT FK_USERS_TO_RESERVATIONS
    FOREIGN KEY (USER_ID)
    REFERENCES USERS (USER_ID);

ALTER TABLE USER_RESERV_QA
  ADD CONSTRAINT FK_RESERVATIONS_TO_USER_RESERV_QA
    FOREIGN KEY (RESERV_ID)
    REFERENCES RESERVATIONS (RESERV_ID);

ALTER TABLE USER_RESERV_QA
  ADD CONSTRAINT FK_QUESTIONS_TO_USER_RESERV_QA
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTIONS (QUESTION_ID);

ALTER TABLE USER_RESERV_QA
  ADD CONSTRAINT FK_ANSWERS_TO_USER_RESERV_QA
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWERS (ANSWER_ID);

ALTER TABLE QUE_ANS
  ADD CONSTRAINT FK_QUESTIONS_TO_QUE_ANS
    FOREIGN KEY (QUESTION_ID)
    REFERENCES QUESTIONS (QUESTION_ID);

ALTER TABLE QUE_ANS
  ADD CONSTRAINT FK_ANSWERS_TO_QUE_ANS
    FOREIGN KEY (ANSWER_ID)
    REFERENCES ANSWERS (ANSWER_ID);
